name: text_auto_direction
description: A Flutter package that provides the AutoDirection widget for automatic text direction detection.
version: 0.0.1
homepage: https://github.com/chieduegbumokei/text_auto_direction

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
